# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import file_viewer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('num_like', models.IntegerField(default=0)),
                ('page_id', models.CharField(max_length=18)),
                ('height_percent', models.FloatField()),
                ('width_percent', models.FloatField()),
                ('top_percent', models.FloatField()),
                ('left_percent', models.FloatField()),
                ('frame_color', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('num_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to=file_viewer.models.upload_to)),
                ('md5', models.CharField(max_length=32)),
            ],
        ),
    ]
