# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='unique_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_viewer.UniqueFile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='document_this_comment_belongs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_viewer.Document'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='document_this_annotation_belongs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_viewer.Document'),
        ),
    ]
