# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='num_of_pages',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
