# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='num_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='collectors',
            field=models.ManyToManyField(related_name='collected_document_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
