# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_viewer.Comment'),
        ),
    ]
