# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Document',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='file_this_comment_belongs',
            new_name='document_this_comment_belongs',
        ),
    ]
