# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_like',
            field=models.IntegerField(default=0),
        ),
    ]
