# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_portrait'),
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('num_like', models.IntegerField(default=0)),
                ('page_id', models.CharField(max_length=18)),
                ('height_percent', models.FloatField()),
                ('width_percent', models.FloatField()),
                ('top_percent', models.FloatField()),
                ('left_percent', models.FloatField()),
                ('frame_color', models.CharField(max_length=18)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
                ('document_this_annotation_belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_viewer.Document')),
            ],
        ),
    ]
