# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0002_auto_20160625_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationreply',
            name='reply_to_annotation_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='file_viewer.AnnotationReply'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='file_viewer.Comment'),
        ),
    ]
