# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('administrators', models.ManyToManyField(related_name='administrated_coterie_set', to=settings.AUTH_USER_MODEL)),
                ('applicants', models.ManyToManyField(blank=True, related_name='appliedd_coterie_set', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_coterie_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
