# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160622_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='_user_following_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
