# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_following_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='follower_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
