# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160516_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_to),
        ),
    ]
